SELECT ID, NAME, HOST_ID
FROM PLACES 
WHERE HOST_ID IN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2
    )
ORDER BY ID ASC

# 각 HOST_ID 당 조건 조회 ! GROUP BY ~ HAVING