SELECT H.HISTORY_ID, 
    FLOOR(
        C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 
        (1 - COALESCE(P.DISCOUNT_RATE / 100.0, 0))
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C 
    ON  H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON  C.CAR_TYPE = P.CAR_TYPE
    AND (
        (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 7 AND P.DURATION_TYPE = "7일 이상"
        OR
        (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 30 AND P.DURATION_TYPE = "30일 이상"
        OR
        (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 90 AND P.DURATION_TYPE = "90일 이상"
    ) 
WHERE C.CAR_TYPE = "트럭"
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC


# 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서
# 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여
# 대여 기록 ID와 대여 금액 리스트를 출력
