SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE
    A.APNT_CNCL_YN = 'N' -- 취소 안됨
    AND A.MCDP_CD = 'CS' -- 흉부외과
    AND DATE(A.APNT_YMD) = '2022-04-13'
ORDER BY A.APNT_YMD ASC
