SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI 
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.LENGTH = (
    SELECT MAX(LENGTH) 
    FROM FISH_INFO
    WHERE FISH_INFO.FISH_TYPE = FI.FISH_TYPE
)
ORDER BY FI.ID ASC







# 물고기 종류별 가장 큰 물고기는 1마리만 있음
